### ISSUE TITLE
obsolete height should result in getting new work

### ISSUE THREAD

**Issue by ahatstat** [Nexusoft/NexusMiner#3]
I saw a case where two blocks were found within one second of each other.  The first was accepted and the second resulted in Obsolete Height, Skipping Over.  The miner kept mining with the obsolete block data and the next block found much later was rejected.  In case obsolete height is detected, it should get new block data.

**Comment by beuschl** [comment]
should be fixed with commit 163fca6cef9cbf9cc1e147076b1d6a752967f86c of v1.1 branch
